In [4]:
import cv2
import numpy as np

In [5]:
path = "butterfly.jpg"

In [9]:
def convolute(img,kernel):
    row,col,c = img.shape
    output = img.copy()
    for i in range(1,row-1):
        for j in range(1,col-1):
            for k in range(c):
                window = img[i-1:i+2,j-1:j+2,k]
                output[i,j,k] = np.sum(np.multiply(window,kernel))
    return output   


def gaussian_blur(img):
    kernel = np.array([[1/16,2/16,1/16],
                       [2/16,4/16,2/16],
                       [1/16,2/16,1/16]])

    return convolute(img,kernel)           

In [10]:
def sobel_filter(img):
    Gy = np.array([[1,2,1],
                    [0,0,0],
                    [-1,-2,-1]])
    Gx = np.array([[1,0,-1],
                    [2,0,-2],
                    [1,0,-1]])
    
    bw_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    bw_img = bw_img.reshape((bw_img.shape[0],bw_img.shape[1],1))
    output = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    X_edge = convolute(bw_img,Gx)
    Y_edge = convolute(bw_img,Gy)
    V = np.sqrt(np.add(np.square(X_edge),np.square(Y_edge)))
    print(V)
    cv2.imshow('Raw',V)
    cv2.waitKey(0)
    # return np.array([V[:,:,0],V[:,:,0],V[:,:,0]])
    H = np.arctan(np.divide(Y_edge,X_edge))*229.18 + 114.59
    print(V.shape)
    print(H.shape)
    output[:,:,0] = H[:,:,0]*1.3
    output[:,:,1] = np.ones(V[:,:,0].shape)*100
    output[:,:,2] = V[:,:,0]
    return cv2.cvtColor(output, cv2.COLOR_HSV2BGR)

In [11]:
img = cv2.imread(path)
row,col,c = img.shape
blured = gaussian_blur(img)

        

In [12]:
blured

array([[[21, 65, 34],
        [21, 65, 34],
        [20, 67, 35],
        ...,
        [19, 47, 24],
        [19, 47, 24],
        [19, 47, 24]],

       [[24, 66, 35],
        [22, 65, 34],
        [21, 66, 35],
        ...,
        [19, 48, 25],
        [20, 48, 25],
        [21, 49, 26]],

       [[25, 66, 35],
        [23, 64, 34],
        [22, 64, 35],
        ...,
        [20, 50, 26],
        [21, 50, 26],
        [22, 52, 27]],

       ...,

       [[11, 65, 35],
        [11, 68, 38],
        [13, 71, 42],
        ...,
        [19, 55, 30],
        [19, 56, 31],
        [21, 57, 33]],

       [[11, 63, 33],
        [11, 66, 36],
        [11, 68, 38],
        ...,
        [15, 50, 26],
        [15, 51, 27],
        [15, 51, 27]],

       [[14, 66, 36],
        [12, 66, 36],
        [10, 66, 37],
        ...,
        [11, 47, 23],
        [10, 46, 22],
        [10, 46, 22]]], dtype=uint8)

In [13]:
    Gy = np.array([[1,2,1],
                    [0,0,0],
                    [-1,-2,-1]])
    Gx = np.array([[1,0,-1],
                    [2,0,-2],
                    [1,0,-1]])
    
    bw_img = cv2.cvtColor(blured, cv2.COLOR_BGR2GRAY)

In [14]:
bw_img

array([[51, 51, 52, ..., 37, 37, 37],
       [52, 51, 52, ..., 38, 38, 39],
       [52, 50, 51, ..., 39, 40, 41],
       ...,
       [50, 53, 56, ..., 43, 44, 46],
       [48, 51, 53, ..., 39, 40, 40],
       [51, 51, 51, ..., 36, 35, 35]], dtype=uint8)

In [15]:
    bw_img = bw_img.reshape((bw_img.shape[0],bw_img.shape[1],1))
    output = cv2.cvtColor(blured, cv2.COLOR_BGR2HSV)
    X_edge = convolute(bw_img,Gx)
    Y_edge = convolute(bw_img,Gy)
    V = np.sqrt(np.add(np.square(X_edge),np.square(Y_edge)))

In [19]:
bw_img[:,:,0]

array([[51, 51, 52, ..., 37, 37, 37],
       [52, 51, 52, ..., 38, 38, 39],
       [52, 50, 51, ..., 39, 40, 41],
       ...,
       [50, 53, 56, ..., 43, 44, 46],
       [48, 51, 53, ..., 39, 40, 40],
       [51, 51, 51, ..., 36, 35, 35]], dtype=uint8)

In [20]:
V[:,:,0].astype(np.)

array([[ 9.055,  9.055,  5.656, ..., 13.34 , 13.34 , 13.34 ],
       [ 5.656,  2.   ,  8.6  , ..., 10.77 , 12.65 , 15.03 ],
       [ 5.656,  9.484, 12.   , ..., 12.65 , 13.414,  5.832],
       ...,
       [11.664,  6.   , 15.3  , ..., 14.   , 15.234, 11.664],
       [ 0.   ,  8.   ,  8.6  , ...,  9.055,  5.656, 11.31 ],
       [ 9.055,  9.055,  9.055, ...,  5.656, 12.086, 12.086]],
      dtype=float16)

In [25]:
        cv2.imshow('Raw',(V[:,:,0]*5).astype('uint8'))
        cv2.waitKey(0)

-1